// Global
export const RESET_STATE = "RESET_STATE";

// Artist
export const SET_ALBUMS = "SET_ALBUMS";
export const SET_ARTIST = "SET_ARTIST";

// Album
export const SET_CURRENT_ALBUM = "SET_CURRENT_ALBUM";
export const SET_CURRENTLY_PLAYING = "SET_CURRENTLY_PLAYING";

// Audio
export const SET_PLAYING_AUDIO = "SET_PLAYING_AUDIO";
export const CLEAR_CURRENTLY_PLAYING = "CLEAR_CURRENTLY_PLAYING";
